name: Build pages
on:
  push:
    branches:
      - any_stubs
  workflow_run:
    workflows: ["Build test"]
    types:
      - completed
env:
  MASTER_BRANCH: refs/heads/master
jobs:
  update-pages:
    runs-on: ubuntu-18.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install rospy-build
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools==51.2.0 wheel
        ./rospy-builder/install.sh
        pip install rospy-builder/
    - name: Generate index html
      run: |
        mkdir index
        rospy-build index index
        rospy-build index --prefix pre index/_pre
    - name: Runs only when tagged or pushed to master
      if: startsWith(github.ref, 'refs/tags/') || github.ref == env.MASTER_BRANCH
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd index
        git init
        git config user.name "Tamaki Nishino"
        git config user.email "otamachan@gmail.com"
        git remote add origin https://otamachan:${GITHUB_TOKEN}@github.com/rospypi/simple.git
        git checkout -b gh-pages
        touch .nojekyll
        git add .
        git commit -am "Release $(date)"
        git push -f origin gh-pages
      shell: bash
